In [5]:
#scalar,vector,linearalgebra
#ATS score

#scalara-> x=4
#vector-> x=[2,3,4,5,7]    one-dimensional datat
#matrix->x=[[2,3],[4,5],[6,7]]   two-dimensional data
#tensor

#numpy-numerical python -> to do mathmatical calculation
#pytorch


import numpy as np
scalar=5
vector=np.array([1,2,3,4,5])
matrix=np.matrix([[1,2],[3,4]])
print(scalar)
print(vector)
print(matrix)

5
[1 2 3 4 5]
[[1 2]
 [3 4]]


In [6]:
import numpy as np
scalar=5
vector=np.array([1,2,3,4,5])
matrix=np.matrix([[1,2],[3,4]])
print(scalar)
print(vector.shape)
print(matrix.shape)

5
(5,)
(2, 2)


In [ ]:
import numpy as np
scalar=5
vector=np.array([1,2,3,4,5])
matrix=np.matrix([[1,2],[3,4]])
print(scalar)
print(vector.ndim)
print(matrix.ndim)

5
1
2


In [11]:
import numpy as np
scalar=5
vector=np.array([1,2,3,4,5])
matrix=np.matrix([[1,2],[3,4],[5,6]])
print(scalar)
print(vector.ndim)
print(matrix.ndim)
print(np.linalg.matrix_rank(matrix))

5
1
2
2


In [12]:
row_wise=np.array([1,2,3])
col_wise=np.array([[1],[2],[3]])
print(row_wise)
print(col_wise)

[1 2 3]
[[1]
 [2]
 [3]]


In [13]:
row_wise=np.array([1,2,3])
col_wise=np.array([[1],[2],[3]])
print(row_wise.shape)
print(col_wise.shape)

(3,)
(3, 1)


In [14]:
row_wise=np.array([1,2,3])
col_wise=np.array([[1],[2],[3]])
print(row_wise.ndim)
print(col_wise.ndim)

1
2


In [15]:
v1=np.array([[1,2],[3,4]])

v2=np.array([[1,2],[3,4]])
print(v1*v2)
print(2*v1)

[[ 1  4]
 [ 9 16]]
[[2 4]
 [6 8]]


In [ ]:
#dot product and normal multiplication

v1=np.array([[1,2],[3,4]])

v2=np.array([[1,2],[3,4]])
print(np.dot(v1,v2))
print()
print(v1*v2)

[[ 7 10]
 [15 22]]

[[ 1  4]
 [ 9 16]]


In [ ]:
#Transpose of a matrix
v1=np.array([[1,2],[3,4]])

print(v1.T)

[[1 3]
 [2 4]]


In [ ]:
#cross product of two vectors
v1=np.array([[1,2],[3,4]])

v2=np.array([[1,2],[3,4]])

print(np.cross(v1,v2))

[0 0]


C:\Users\mohammed razeen\AppData\Local\Temp\ipykernel_780\3027036088.py:5: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(v1,v2))


In [ ]:
v1=np.array([[1,2,3,4],[5,6,7,8]])

v2=np.array([[5,6,7,8],[0,]])

In [21]:
v1=np.array([[1,2,3],[7,9,6]])
v2=np.array([[4,5,6],[9,5,6]])
cross=np.cross(v1,v2)
print(cross)

[[ -3   6  -3]
 [ 24  12 -46]]


In [ ]:
A=[1,2,3]
B=[4,5,6]
#use dot product
#output 32
print(np.dot(A, B)) 



32


In [23]:
A=[1,2,3]
B=[4,5,6]

result=0

for i in range(len(A)):
    result+=A[i]*B[i]
print(result)

32


In [ ]:
A=[1,2,3]
B=[4,5,6]


#input [[1,2,3],[4,5,6]]
#output [[1 4]
#        [2 5]
#        [3 6]]


transpose=0
for col in range(len(A)):
    



In [2]:
m = [[1, 2, 3],[4, 5, 6]]

rows = len(m)
cols = len(m[0])
T = []
for j in range(cols):
    new_row=[]
    for i in range(rows):
        new_row.append(m[i][j])
    T.append(new_row)
print("Transpose:")
for row in T:
    print(row)


Transpose:
[1, 4]
[2, 5]
[3, 6]
